### ISSUE TITLE
Site title color in 6.6

### ISSUE THREAD

**Issue by nc-mhenderson** [utkwdn/utkwds#370] opened 2024-07-01 20:06 UTC
**Describe the bug**
Site title link turns blue in wp 6.6

**WDS Theme Version**

1.1.5

**Expected behavior**
site title should remain black

**Screenshots**
<img width="1126" alt="Screenshot 2024-07-01 at 2 04 25 PM" src="https://github.com/utkwdn/utkwds/assets/107649073/e4b43e0f-9b39-44e3-83c6-72b8ba95f786">

**Additional context**

**Comment by reasterbrooknc** [comment] 2024-07-29 18:15
duplicate of #382

**Closed by reasterbrooknc** 2024-07-29 18:15 UTC
Labels: Bug Fixing
