### ISSUE TITLE
Fancy Link

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#130] opened 2023-10-20 18:08 UTC
Exiting feedback for 1.2:
- [ ] Hard to edit (changing words is very difficult)

**Comment by kellieward** [comment] 2023-12-05 16:35
Looks good to me. Easier to edit.

**Comment by reasterbrooknc** [comment] 2024-03-29 18:47
- Rename CTA link
- Rebuild so it isn't paragraph

**Comment by reasterbrooknc** [comment] 2024-06-12 17:26
Duplicate of #291

**Closed by reasterbrooknc** 2024-06-12 17:26 UTC
