### ISSUE TITLE
New Hero Rendering makes it hard to edit the content

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#385] opened 2024-07-19 18:35 UTC
**Describe the bug**
New Hero (Full-Width Hero) Rendering makes it hard to edit the content below it. 
Within the Gutenberg blocks, you cannot add another component beneath the  Full-Width hero by hitting the + sign. If you hit the black plus sign when you select the small white box with the text, it inserts everything into that box. If you hit the plus sign that is farther to the right, it inserts the component into the picture. It can work in the list view or you can add an element above it and use the arrows to move it down.

**Page URL**
https://wds-stg.utk.edu/wp-admin/post.php?post=63469&action=edit

**WDS Theme Version**
1.1.5

**To Reproduce**
1. Add the new Hero
2. Click on the black plus near the bottom of the editor
3. Insert content

**Expected behavior**
Expect the inserted content to be outside the hero group, down the page.

**Screenshots**
https://brand.utk.edu/web-design-system/index.php?gf-download=2024%2F06%2FScreenshot-2024-06-26-at-3.11.16-PM.png&form-id=1&field-id=7&hash=f7e80b86c0b5539bcdc2215e5a4b876daadaf3f9dfdee01870d40b7970164663

https://brand.utk.edu/web-design-system/index.php?gf-download=2024%2F06%2FScreenshot-2024-06-26-at-3.10.32-PM.png&form-id=1&field-id=7&hash=256baf4bb807831ffea97df70fea470caeb507de9d15bc9f6284d2eb107db593

**Desktop (please complete the following information):**
 - OS: MacOS 13 & MacOS 14
 - Browser Chrome & safari. Probably everywhere

**Comment by reasterbrooknc** [comment] 2024-07-29 18:12
duplicate of #384

**Closed by reasterbrooknc** 2024-07-29 18:12 UTC
Labels: Bug Fixing
